package com.intellij.spring.security.model.xml;

/**
 * http://www.springframework.org/schema/security:named-security-filter enumeration.
 */
public enum NamedSecurityFilter {
  ANONYMOUS_FILTER,
  AUTHENTICATION_PROCESSING_FILTER,
  BASIC_PROCESSING_FILTER,
  CAS_PROCESSING_FILTER,
  CHANNEL_FILTER,
  CONCURRENT_SESSION_FILTER,
  EXCEPTION_TRANSLATION_FILTER,
  FILTER_SECURITY_INTERCEPTOR,
  FIRST,
  LAST,
  LOGOUT_FILTER,
  NTLM_FILTER,
  OPENID_PROCESSING_FILTER,
  PRE_AUTH_FILTER,
  REMEMBER_ME_FILTER,
  SERVLET_API_SUPPORT_FILTER,
  SESSION_CONTEXT_INTEGRATION_FILTER,
  SWITCH_USER_FILTER,
  X509_FILTER
}
